name: monet-docs

channels:
  - conda-forge

dependencies:
  - python=3.6
  - cartopy=0.17.0
  - pip
  - pip:
    - matplotlib
    - sphinx==2.1.2
    - sphinx_rtd_theme==0.4.3
    - numpy
    - xarray
    - seaborn

